In [1]:
import pandas as pd

hashtags = pd.read_csv('news_hashtags.csv')
creaters = pd.read_csv('news_creaters.csv')

In [12]:
hashtags
hashtags_list = hashtags['Hashtag name'].tolist()

In [15]:
creaters
creaters_list = creaters['Username'].tolist()

In [9]:
data_to_filter = pd.read_csv('TEST-results.csv') #change this line to parse different files
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
0,7280779115760733482,2023-09-20T01:41:38,321,US,NaN,2206,150,59,19500,#stitch with @hasty some of you probably prono...,False,NaN,failedviner,Tan | failedviner,NaN,NaN,NaN,NaN,NaN,False
1,7338804441702862111,2024-02-23T09:29:40,8,US,"Cap Cut Template, capcut edit templates, templ...",22300,102,356,883900,#CapCut @‚öúÔ∏èinxky‚öúÔ∏è #fyp #viral #template #capc...,False,NaN,capcuttemplatesthatifind,findingtemplatesforyou,NaN,NaN,NaN,NaN,NaN,False
2,7281173547069001006,2023-09-21T03:12:16,12,GB,NaN,23,0,0,483,NaN,False,NaN,.junonia,natalie,NaN,NaN,NaN,NaN,NaN,False
3,7280261400805575966,2023-09-18T16:12:43,0,GB,NaN,41,0,6,544,NaN,False,NaN,.junonia,natalie,NaN,NaN,NaN,NaN,NaN,False
4,7333422897228156202,2024-02-08T21:26:32,14,AU,"Scott Disick, penelope kardashians, Pandkourt,...",351400,676,0,2200000,NaN,False,NaN,pandkourt,Kourtney-Penelope,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7342267799882009888,2024-03-03T17:29:09,12,GB,"alex consani, alex consani runway, alex consan...",774400,1050,777,4800000,Replying to @Caitlin Jones310 Backstage with @...,False,NaN,dazed,dazed,NaN,NaN,NaN,NaN,NaN,True
194,7341537402684525866,2024-03-01T18:15:05,10,US,"back on 74 dance, back on 74 by jungle, back t...",165900,171,234,619100,NaN,False,NaN,prejoye,precious,NaN,NaN,NaN,NaN,NaN,False
195,7337846537759771950,2024-02-20T19:32:26,17,US,"dune 2 edit, Dune, Dune Movie, timoth√©e chalam...",88600,657,228,434500,for this lil' #askthedunecast i want to know t...,False,NaN,ashlliex,ellie williams,NaN,NaN,NaN,NaN,NaN,False
196,7339339777281510698,2024-02-24T20:07:20,61,US,"mark sloan, mark and lexie, mcdreamy, mark slo...",1100000,6539,2782,4200000,Mcsteamyüòçüòçüòç #marksloan #marksloanedit #greysan...,False,NaN,greysan19,üóø,NaN,NaN,NaN,NaN,NaN,False
197,7338499139531017474,2024-02-22T13:44:41,16,FAKE-AD,"Fitness Training, Fitness TikTok, fitness work...",539,4,4,157400,Teaching fitness can take you places you only ...,True,NaN,Les Mills,Les Mills,NaN,NaN,NaN,NaN,NaN,False

In [11]:
import re
def getHashtags(phrase):
    if isinstance(phrase, str):
        return re.findall(r'#(\S+)', phrase.lower())
    else:
        return []

data_to_filter['hashtags'] = data_to_filter['video_description'].apply(getHashtags)
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,...,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified,hashtags
0,7280779115760733482,2023-09-20T01:41:38,321,US,NaN,2206,150,59,19500,#stitch with @hasty some of you probably prono...,...,NaN,failedviner,Tan | failedviner,NaN,NaN,NaN,NaN,NaN,False,"[stitch, pokemon, videogames, smogon, vgc, ani..."
1,7338804441702862111,2024-02-23T09:29:40,8,US,"Cap Cut Template, capcut edit templates, templ...",22300,102,356,883900,#CapCut @‚öúÔ∏èinxky‚öúÔ∏è #fyp #viral #template #capc...,...,NaN,capcuttemplatesthatifind,findingtemplatesforyou,NaN,NaN,NaN,NaN,NaN,False,"[capcut, fyp, viral, template, capcut, edit]"
2,7281173547069001006,2023-09-21T03:12:16,12,GB,NaN,23,0,0,483,NaN,...,NaN,.junonia,natalie,NaN,NaN,NaN,NaN,NaN,False,[]
3,7280261400805575966,2023-09-18T16:12:43,0,GB,NaN,41,0,6,544,NaN,...,NaN,.junonia,natalie,NaN,NaN,NaN,NaN,NaN,False,[]
4,7333422897228156202,2024-02-08T21:26:32,14,AU,"Scott Disick, penelope kardashians, Pandkourt,...",351400,676,0,2200000,NaN,...,NaN,pandkourt,Kourtney-Penelope,NaN,NaN,NaN,NaN,NaN,True,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7342267799882009888,2024-03-03T17:29:09,12,GB,"alex consani, alex consani runway, alex consan...",774400,1050,777,4800000,Replying to @Caitlin Jones310 Backstage with @...,...,NaN,dazed,dazed,NaN,NaN,NaN,NaN,NaN,True,"[dazedfashiontv, tiktokfashion, alexconsani, m..."
194,7341537402684525866,2024-03-01T18:15:05,10,US,"back on 74 dance, back on 74 by jungle, back t...",165900,171,234,619100,NaN,...,NaN,prejoye,precious,NaN,NaN,NaN,NaN,NaN,False,[]
195,7337846537759771950,2024-02-20T19:32:26,17,US,"dune 2 edit, Dune, Dune Movie, timoth√©e chalam...",88600,657,228,434500,for this lil' #askthedunecast i want to know t...,...,NaN,ashlliex,ellie williams,NaN,NaN,NaN,NaN,NaN,False,"[askthedunecast, ashlliex, dune, dunemovie, du..."
196,7339339777281510698,2024-02-24T20:07:20,61,US,"mark sloan, mark and lexie, mcdreamy, mark slo...",1100000,6539,2782,4200000,Mcsteamyüòçüòçüòç #marksloan #marksloanedit #greysan...,...,NaN,greysan19,üóø,NaN,NaN,NaN,NaN,NaN,False,"[marksloan, marksloanedit, greysanatomy, greys..."
197,7338499139531017474,2024-02-22T13:44:41,16,FAKE-AD,"Fitness Training, Fitness TikTok, fitness work...",539,4,4,157400,Teaching fitness can take you places you only ...,...,NaN,Les Mills,Les Mills,NaN,NaN,NaN,NaN,NaN,False,[]

In [21]:
newsDF = data_to_filter[data_to_filter.apply(lambda row: 
                      (isinstance(row['hashtags'], list) and 
                       any(hashtag in row['hashtags'] for hashtag in hashtags_list)) 
                      or row['author_username'] in creaters_list, axis=1)]

## if hashtags is indeed a list, check if there is overlap between the video hashtag and the hashtag list or if the video 
## content creator is a news account. If any of the two is satisfied, pass to new dataset newsDF.

In [17]:
newsDF
## This result is actually a bit too weird

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,...,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified,hashtags
89,7342623988755057966,2024-03-04T16:31:46,0,US,"Russell Wilson, broncos, Denver Broncos, NFL F...",9286,584,607,499700,Breaking: The Denver #Broncos announced that t...,...,NaN,espn,ESPN,NaN,NaN,NaN,NaN,NaN,True,"[broncos, russellwilson, nfl, football]"
135,7338257395610602782,2024-02-21T22:07:09,20,US,"Messi, inter miami, lionel messi, Leo Messi In...",336500,8976,4005,5100000,THIS MESSI MOVE. ü§Øü§Ø #lionelmessi #messi #inter...,...,NaN,houseofhighlights,House of Highlights,NaN,NaN,NaN,NaN,NaN,True,"[lionelmessi, messi, intermiami, mls, football..."
143,7339575392237407521,2024-02-25T11:21:11,15,IT,"Travis Kelce SNL, travis kelce edits, travis k...",342000,5087,1550,2300000,TRAVIS KELCE?üó£üó£ #nfl #traviskelce #travis #kel...,...,NaN,travkelce13,tkelce13,NaN,NaN,NaN,NaN,NaN,False,"[nfl, traviskelce, travis, kelce, fyp, edit, v..."
150,7342621870191201582,2024-03-04T16:23:33,0,US,"russell wilson, russell wilson release, bronco...",75900,1345,1995,952800,üö® Breaking: Russell Wilson has been released b...,...,NaN,bleacherreport,bleacherreport,NaN,NaN,NaN,NaN,NaN,True,"[nfl, nflfootball, football]"
156,7340477137285287214,2024-02-27T21:40:27,66,US,"calvin ridley, nightcrawler edit, Football Pla...",76400,85,247,474900,this kinda sucks but i forgot to post it #nfl ...,...,NaN,jaguarpost,ùïµùñÜùñåùñöùñÜùñó,NaN,NaN,NaN,NaN,NaN,False,"[nfl, sports, calvinridley, jaguars, jacksovil..."