In [250]:
import pandas as pd

hashtags = pd.read_csv('news_hashtags.csv')
creaters = pd.read_csv('news_creaters.csv')

In [251]:
hashtags
hashtags_list = hashtags['Hashtag name'].tolist()

In [252]:
#hashtags_list

In [253]:
creaters
creaters_list = creaters['Username'].tolist()

In [254]:
#creaters_list

In [255]:
dir_path = "/Users/sandyliu/tiktok-news-exposure/" # CHANGE ME!

In [256]:
file_to_process = dir_path + "2-collect-metadata-pyktok/final-metadata/results_69117.csv"
data_to_filter = pd.read_csv(file_to_process) #change this line to parse different files
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
0,7315561816673750318,2023-12-22T18:16:20,18.0,US,"flipnote, flipnote animation, asdf movie, flip...",3600000.0,40100.0,11000.0,19000000.0,Bonus flipnote for you,False,NaN,zanelittlemusic,Zane Little,NaN,NaN,NaN,NaN,NaN,False
1,7331462048699649323,2024-02-03T14:37:35,8.0,US,NaN,1111.0,1.0,2.0,6589.0,‚òÅÔ∏èüìô,False,NaN,createbyua,ua,NaN,NaN,NaN,NaN,NaN,False
2,7318253025649315104,2023-12-30T00:21:20,6.0,TH,NaN,2208.0,3.0,8.0,42400.0,at 30 & 25 years of age üòÇüòÇ,False,NaN,confusedindiangirl,Savannah Sachdev,NaN,NaN,NaN,NaN,NaN,False
3,7331462048699649323,2024-02-03T14:37:35,8.0,US,NaN,1111.0,1.0,2.0,6589.0,‚òÅÔ∏èüìô,False,NaN,createbyua,ua,NaN,NaN,NaN,NaN,NaN,False
4,7318253025649315104,2023-12-30T00:21:20,6.0,TH,NaN,2208.0,3.0,8.0,42400.0,at 30 & 25 years of age üòÇüòÇ,False,NaN,confusedindiangirl,Savannah Sachdev,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15759,7318722296863149345,2023-12-31T06:40:36,16,DE,NaN,522300,23900,3032,9400000,Da muss SIE doch dran denkenüò±üòÇ!!! #viral #f√ºrd...,False,NaN,marie_tammo,ùêåùêöùê´ùê¢ùêû & ùêìùêöùê¶ùê¶ùê®,NaN,NaN,NaN,NaN,NaN,False
15760,7335885936724692266,2024-02-15T12:45:09,9,US,"Megatron Family Guy, parents aren't home you k...",12100000,113100,26700,66400000,Hes just a kitten but thats my dawg,False,NaN,kyle.christie,Kyle Christie,NaN,NaN,NaN,NaN,NaN,False
15761,7338069156064988458,2024-02-21T09:57:03,36,US,"Car Air Freshener, Car Freshener, Car Freshene...",33300,3107,148,2100000,"If you often smoke in the car, you really need...",True,NaN,chidsj,Decsteamboy us,NaN,NaN,NaN,NaN,NaN,False
15762,7331930122397797675,2024-02-04T20:53:59,48,US,"car accessories, car charger, retractable car ...",1200000,37800,8297,35800000,Replying to @DK BOSE this car charger soothes ...,False,NaN,insaneshopfinds,Insane TikTok Shop Deals üéÅ,NaN,NaN,NaN,NaN,NaN,False
15763,7304812867675491626,2023-11-23T19:04:52,98,US,"Halara Leggings, halara, Halara Pants, Legging...",344400,8355,2864,18000000,When i showed these to my husband he said and ...,True,NaN,alexisjohnson1019,Alexis Johnson,NaN,NaN,NaN,NaN,NaN,False

In [257]:
data_to_filter = data_to_filter.loc[data_to_filter['video_locationcreated'] == 'US']

In [258]:
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
0,7315561816673750318,2023-12-22T18:16:20,18.0,US,"flipnote, flipnote animation, asdf movie, flip...",3600000.0,40100.0,11000.0,19000000.0,Bonus flipnote for you,False,NaN,zanelittlemusic,Zane Little,NaN,NaN,NaN,NaN,NaN,False
1,7331462048699649323,2024-02-03T14:37:35,8.0,US,NaN,1111.0,1.0,2.0,6589.0,‚òÅÔ∏èüìô,False,NaN,createbyua,ua,NaN,NaN,NaN,NaN,NaN,False
3,7331462048699649323,2024-02-03T14:37:35,8.0,US,NaN,1111.0,1.0,2.0,6589.0,‚òÅÔ∏èüìô,False,NaN,createbyua,ua,NaN,NaN,NaN,NaN,NaN,False
5,7331462048699649323,2024-02-03T14:37:35,8.0,US,NaN,1111.0,1.0,2.0,6589.0,‚òÅÔ∏èüìô,False,NaN,createbyua,ua,NaN,NaN,NaN,NaN,NaN,False
7,7322969142024342826,2024-01-11T17:20:34,5.0,US,NaN,196.0,0.0,7.0,5198.0,ü•¥üòÖüëçüèæ #vegan #chipotle #veggie #food,False,NaN,darlene_octavia,darleneoctavia,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15758,7312626714775932190,2023-12-14T20:26:40,7,US,NaN,147500,870,3916,1500000,guess the last 4 digits of my phone # ‚òéÔ∏è @Gavi...,False,NaN,lovealwayspiper,Piper,NaN,NaN,NaN,NaN,NaN,False
15760,7335885936724692266,2024-02-15T12:45:09,9,US,"Megatron Family Guy, parents aren't home you k...",12100000,113100,26700,66400000,Hes just a kitten but thats my dawg,False,NaN,kyle.christie,Kyle Christie,NaN,NaN,NaN,NaN,NaN,False
15761,7338069156064988458,2024-02-21T09:57:03,36,US,"Car Air Freshener, Car Freshener, Car Freshene...",33300,3107,148,2100000,"If you often smoke in the car, you really need...",True,NaN,chidsj,Decsteamboy us,NaN,NaN,NaN,NaN,NaN,False
15762,7331930122397797675,2024-02-04T20:53:59,48,US,"car accessories, car charger, retractable car ...",1200000,37800,8297,35800000,Replying to @DK BOSE this car charger soothes ...,False,NaN,insaneshopfinds,Insane TikTok Shop Deals üéÅ,NaN,NaN,NaN,NaN,NaN,False
15763,7304812867675491626,2023-11-23T19:04:52,98,US,"Halara Leggings, halara, Halara Pants, Legging...",344400,8355,2864,18000000,When i showed these to my husband he said and ...,True,NaN,alexisjohnson1019,Alexis Johnson,NaN,NaN,NaN,NaN,NaN,False

In [259]:
data_to_filter = data_to_filter.loc[data_to_filter['video_is_ad'] == False]

In [260]:
data_to_filter

Empty DataFrame
Columns: [video_id, video_timestamp, video_duration, video_locationcreated, suggested_words, video_diggcount, video_sharecount, video_commentcount, video_playcount, video_description, video_is_ad, video_stickers, author_username, author_name, author_followercount, author_followingcount, author_heartcount, author_videocount, author_diggcount, author_verified]
Index: []

In [261]:
import re
def getHashtags(phrase):
    if isinstance(phrase, str):
        return re.findall(r'#(\S+)', phrase.lower())
    else:
        return []

data_to_filter['hashtags'] = data_to_filter['video_description'].apply(getHashtags)

def getSuggestedWords(phrase):
    if phrase is None:
        return []
    elif isinstance(phrase, str):
        return phrase.split(',')
    else:
        return []
    
data_to_filter['suggested_words'] = data_to_filter['suggested_words'].apply(getSuggestedWords)

In [262]:
data_to_filter

Empty DataFrame
Columns: [video_id, video_timestamp, video_duration, video_locationcreated, suggested_words, video_diggcount, video_sharecount, video_commentcount, video_playcount, video_description, video_is_ad, video_stickers, author_username, author_name, author_followercount, author_followingcount, author_heartcount, author_videocount, author_diggcount, author_verified, hashtags]
Index: []

[0 rows x 21 columns]

In [263]:
def filter_conditions(row):
    has_hashtag = isinstance(row['hashtags'], list) and any(hashtag in row['hashtags'] for hashtag in hashtags_list)
    is_creator = row['author_username'] in creaters_list
    has_suggested_word = isinstance(row['suggested_words'], list) and any(word in row['suggested_words'] for word in hashtags_list)
    
    return has_hashtag or is_creator or has_suggested_word

data_to_filter_result = data_to_filter[data_to_filter.apply(filter_conditions, axis=1)]

## if hashtags is indeed a list, check if there is overlap between the video hashtag and the hashtag list or if the video 
## content creator is a news account. If any of the two is satisfied, pass to new dataset newsDF.

In [264]:
data_to_filter_result
## This result is actually a bit too weird

Empty DataFrame
Columns: []
Index: []

In [265]:
file_name = 'new_relevant_videos.csv' #change as needed
with open(file_name, 'w') as fout:
    data_to_filter_result.to_csv('new_relevant_videos_69117.csv')