In [1]:
import pandas as pd

hashtags = pd.read_csv('news_hashtags.csv')
creaters = pd.read_csv('news_creaters.csv')

In [2]:
hashtags
hashtags_list = hashtags['Hashtag name'].tolist()

In [3]:
#hashtags_list

In [4]:
creaters
creaters_list = creaters['Username'].tolist()

In [5]:
#creaters_list

In [6]:
dir_path = "/Users/sandyliu/tiktok-news-exposure/" # CHANGE ME!

In [7]:
file_to_process = dir_path + "2-collect-metadata-pyktok/final-metadata/results_48271.csv"
data_to_filter = pd.read_csv(file_to_process) #change this line to parse different files
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
0,7285457617009315105,2023-10-02T16:16:32,0.0,DE,NaN,98900.0,106700.0,2975.0,1900000.0,#redthoughts #redthoughtsforhim #redthoughtsfo...,False,NaN,red.thoughts2641,üíãred thougtsüòè,NaN,NaN,NaN,NaN,NaN,False
1,7283865333583088929,2023-09-28T09:17:42,46.0,GB,"jake and amy, amy dork dance, brooklyn 99, jak...",627800.0,2675.0,443.0,4700000.0,"teddy vs jake, there‚Äôs just no competition #br...",False,NaN,brooklyn99,Brooklyn Nine-Nine,NaN,NaN,NaN,NaN,NaN,True
2,7283836923393625377,2023-09-28T07:29:43,60.0,PL,NaN,28900.0,4156.0,169.0,228400.0,2 INSANE CT FLASHES on CS2 MIRAGE #cs2 #cs2bet...,False,NaN,cs2_is_broken,cs2_is_broken,NaN,NaN,NaN,NaN,NaN,False
3,7267737378737966341,2023-08-15T22:12:55,190.0,CA,NaN,784000.0,14600.0,697.0,3900000.0,#theoffice #funny #noworkdone #foryou #fyp #th...,False,NaN,theofficebloopurs,bloopers.com,NaN,NaN,NaN,NaN,NaN,False
4,7287677413025123615,2023-10-08T15:50:31,35.0,US,NaN,45600.0,1335.0,114.0,673000.0,And believe it or not‚Ä¶ the same price if not c...,False,NaN,devourpower,DEVOURPOWER,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,7280374358101527840,2023-09-19T17:45:00,165.0,US,NaN,323500.0,9782.0,3184.0,3200000.0,My Ex DUMPED Me to GET HER KITTY POUNDED by SW...,False,NaN,reddits.stories,Reddit‚Äòs Stories,NaN,NaN,NaN,NaN,NaN,False
584,7273366749246967046,2023-08-31T02:17:45,66.0,MX,NaN,3022.0,146.0,33.0,52400.0,#cyphersetup #cyphervalorant #breezevalorant,False,NaN,yizuskrayz,Yizus Krayz,NaN,NaN,NaN,NaN,NaN,False
585,7279732628268436769,2023-09-17T06:00:39,11.0,TN,NaN,173800.0,19000.0,1369.0,1100000.0,#tvshow #petergriffin #english,False,NaN,cartoonviralclips,funny cartoon clips,NaN,NaN,NaN,NaN,NaN,False
586,7279412251474316587,2023-09-16T09:17:39,0.0,US,NaN,1400000.0,351100.0,18900.0,10100000.0,#fyp #foru #babykittenrizz #babykitten #kitten...,False,NaN,kitty.rizzler,Kitty Rizzler,NaN,NaN,NaN,NaN,NaN,False
587,7280444523203808554,2023-09-19T04:03:18,158.0,US,"Pallas Cats, Cats Videos, Animal Videos, Anima...",113600.0,9421.0,582.0,852200.0,#wildlife #kitten #cat #animal,False,NaN,animaltracks789,Animal Tracks,NaN,NaN,NaN,NaN,NaN,False

In [8]:
data_to_filter = data_to_filter.loc[data_to_filter['video_locationcreated'] == 'US']

In [9]:
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
4,7287677413025123615,2023-10-08T15:50:31,35.0,US,NaN,45600.0,1335.0,114.0,673000.0,And believe it or not‚Ä¶ the same price if not c...,False,NaN,devourpower,DEVOURPOWER,NaN,NaN,NaN,NaN,NaN,True
5,7276098613892156705,2023-09-07T10:58:51,21.0,US,NaN,190900.0,21200.0,852.0,4000000.0,The End ü§£ü§£ #funny #funnyvideos #animals #dog #...,False,NaN,theminecracftassistant,Meme Minecracftü§©,NaN,NaN,NaN,NaN,NaN,False
6,7287220444371881259,2023-10-07T10:17:23,303.0,US,NaN,196100.0,498.0,858.0,2900000.0,Part1#storytime #foryou #story #fyp„Ç∑„Çöviral,False,NaN,storyspin1,StorySpin,NaN,NaN,NaN,NaN,NaN,False
7,7288375239770164522,2023-10-10T12:58:28,0.0,US,NaN,1559.0,618.0,8.0,24800.0,#fyp #memes #memestiktok #funny #meme #twitter,False,NaN,ashlynjadeb,ash,NaN,NaN,NaN,NaN,NaN,False
8,7288341455687503134,2023-10-10T10:47:22,6.0,US,NaN,356700.0,79500.0,607.0,2400000.0,NaN,False,NaN,mcdonnelldouglas_f15e,McDonnell Douglas F-15E,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,7279551375749467423,2023-09-16T18:17:26,162.0,US,NaN,490400.0,27100.0,756.0,4300000.0,P*ssy Navy Seals #navyseal,False,NaN,hustlerpotentiall,HUSTLERPOTENTIAL,NaN,NaN,NaN,NaN,NaN,False
579,7279124796749663534,2023-09-15T14:42:06,100.0,US,NaN,95500.0,235.0,53.0,954300.0,#fyp #tiktok #movie #foryou,False,NaN,user85615408784000,Richard,NaN,NaN,NaN,NaN,NaN,False
583,7280374358101527840,2023-09-19T17:45:00,165.0,US,NaN,323500.0,9782.0,3184.0,3200000.0,My Ex DUMPED Me to GET HER KITTY POUNDED by SW...,False,NaN,reddits.stories,Reddit‚Äòs Stories,NaN,NaN,NaN,NaN,NaN,False
586,7279412251474316587,2023-09-16T09:17:39,0.0,US,NaN,1400000.0,351100.0,18900.0,10100000.0,#fyp #foru #babykittenrizz #babykitten #kitten...,False,NaN,kitty.rizzler,Kitty Rizzler,NaN,NaN,NaN,NaN,NaN,False
587,7280444523203808554,2023-09-19T04:03:18,158.0,US,"Pallas Cats, Cats Videos, Animal Videos, Anima...",113600.0,9421.0,582.0,852200.0,#wildlife #kitten #cat #animal,False,NaN,animaltracks789,Animal Tracks,NaN,NaN,NaN,NaN,NaN,False

In [10]:
data_to_filter = data_to_filter.loc[data_to_filter['video_is_ad'] == False]

In [11]:
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
4,7287677413025123615,2023-10-08T15:50:31,35.0,US,NaN,45600.0,1335.0,114.0,673000.0,And believe it or not‚Ä¶ the same price if not c...,False,NaN,devourpower,DEVOURPOWER,NaN,NaN,NaN,NaN,NaN,True
5,7276098613892156705,2023-09-07T10:58:51,21.0,US,NaN,190900.0,21200.0,852.0,4000000.0,The End ü§£ü§£ #funny #funnyvideos #animals #dog #...,False,NaN,theminecracftassistant,Meme Minecracftü§©,NaN,NaN,NaN,NaN,NaN,False
6,7287220444371881259,2023-10-07T10:17:23,303.0,US,NaN,196100.0,498.0,858.0,2900000.0,Part1#storytime #foryou #story #fyp„Ç∑„Çöviral,False,NaN,storyspin1,StorySpin,NaN,NaN,NaN,NaN,NaN,False
7,7288375239770164522,2023-10-10T12:58:28,0.0,US,NaN,1559.0,618.0,8.0,24800.0,#fyp #memes #memestiktok #funny #meme #twitter,False,NaN,ashlynjadeb,ash,NaN,NaN,NaN,NaN,NaN,False
8,7288341455687503134,2023-10-10T10:47:22,6.0,US,NaN,356700.0,79500.0,607.0,2400000.0,NaN,False,NaN,mcdonnelldouglas_f15e,McDonnell Douglas F-15E,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,7279551375749467423,2023-09-16T18:17:26,162.0,US,NaN,490400.0,27100.0,756.0,4300000.0,P*ssy Navy Seals #navyseal,False,NaN,hustlerpotentiall,HUSTLERPOTENTIAL,NaN,NaN,NaN,NaN,NaN,False
579,7279124796749663534,2023-09-15T14:42:06,100.0,US,NaN,95500.0,235.0,53.0,954300.0,#fyp #tiktok #movie #foryou,False,NaN,user85615408784000,Richard,NaN,NaN,NaN,NaN,NaN,False
583,7280374358101527840,2023-09-19T17:45:00,165.0,US,NaN,323500.0,9782.0,3184.0,3200000.0,My Ex DUMPED Me to GET HER KITTY POUNDED by SW...,False,NaN,reddits.stories,Reddit‚Äòs Stories,NaN,NaN,NaN,NaN,NaN,False
586,7279412251474316587,2023-09-16T09:17:39,0.0,US,NaN,1400000.0,351100.0,18900.0,10100000.0,#fyp #foru #babykittenrizz #babykitten #kitten...,False,NaN,kitty.rizzler,Kitty Rizzler,NaN,NaN,NaN,NaN,NaN,False
587,7280444523203808554,2023-09-19T04:03:18,158.0,US,"Pallas Cats, Cats Videos, Animal Videos, Anima...",113600.0,9421.0,582.0,852200.0,#wildlife #kitten #cat #animal,False,NaN,animaltracks789,Animal Tracks,NaN,NaN,NaN,NaN,NaN,False

In [12]:
import re
def getHashtags(phrase):
    if isinstance(phrase, str):
        return re.findall(r'#(\S+)', phrase.lower())
    else:
        return []

data_to_filter['hashtags'] = data_to_filter['video_description'].apply(getHashtags)

def getSuggestedWords(phrase):
    if phrase is None:
        return []
    elif isinstance(phrase, str):
        return phrase.split(',')
    else:
        return []
    
data_to_filter['suggested_words'] = data_to_filter['suggested_words'].apply(getSuggestedWords)

/var/folders/s4/ppn80whx7vncf15l68hxt0tm0000gn/T/ipykernel_39653/1592711010.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_to_filter['hashtags'] = data_to_filter['video_description'].apply(getHashtags)
/var/folders/s4/ppn80whx7vncf15l68hxt0tm0000gn/T/ipykernel_39653/1592711010.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_to_filter['suggested_words'] = data_to_filter['suggested_words'].apply(getSuggestedWords)

In [13]:
data_to_filter

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,...,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified,hashtags
4,7287677413025123615,2023-10-08T15:50:31,35.0,US,[],45600.0,1335.0,114.0,673000.0,And believe it or not‚Ä¶ the same price if not c...,...,NaN,devourpower,DEVOURPOWER,NaN,NaN,NaN,NaN,NaN,True,"[devourpower, fyp, foryou, foodtiktok, crownhe..."
5,7276098613892156705,2023-09-07T10:58:51,21.0,US,[],190900.0,21200.0,852.0,4000000.0,The End ü§£ü§£ #funny #funnyvideos #animals #dog #...,...,NaN,theminecracftassistant,Meme Minecracftü§©,NaN,NaN,NaN,NaN,NaN,False,"[funny, funnyvideos, animals, dog, cat, pet, v..."
6,7287220444371881259,2023-10-07T10:17:23,303.0,US,[],196100.0,498.0,858.0,2900000.0,Part1#storytime #foryou #story #fyp„Ç∑„Çöviral,...,NaN,storyspin1,StorySpin,NaN,NaN,NaN,NaN,NaN,False,"[storytime, foryou, story, fyp„Ç∑„Çöviral]"
7,7288375239770164522,2023-10-10T12:58:28,0.0,US,[],1559.0,618.0,8.0,24800.0,#fyp #memes #memestiktok #funny #meme #twitter,...,NaN,ashlynjadeb,ash,NaN,NaN,NaN,NaN,NaN,False,"[fyp, memes, memestiktok, funny, meme, twitter]"
8,7288341455687503134,2023-10-10T10:47:22,6.0,US,[],356700.0,79500.0,607.0,2400000.0,NaN,...,NaN,mcdonnelldouglas_f15e,McDonnell Douglas F-15E,NaN,NaN,NaN,NaN,NaN,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,7279551375749467423,2023-09-16T18:17:26,162.0,US,[],490400.0,27100.0,756.0,4300000.0,P*ssy Navy Seals #navyseal,...,NaN,hustlerpotentiall,HUSTLERPOTENTIAL,NaN,NaN,NaN,NaN,NaN,False,[navyseal]
579,7279124796749663534,2023-09-15T14:42:06,100.0,US,[],95500.0,235.0,53.0,954300.0,#fyp #tiktok #movie #foryou,...,NaN,user85615408784000,Richard,NaN,NaN,NaN,NaN,NaN,False,"[fyp, tiktok, movie, foryou]"
583,7280374358101527840,2023-09-19T17:45:00,165.0,US,[],323500.0,9782.0,3184.0,3200000.0,My Ex DUMPED Me to GET HER KITTY POUNDED by SW...,...,NaN,reddits.stories,Reddit‚Äòs Stories,NaN,NaN,NaN,NaN,NaN,False,"[reddit, redditstories, redditreadings, askred..."
586,7279412251474316587,2023-09-16T09:17:39,0.0,US,[],1400000.0,351100.0,18900.0,10100000.0,#fyp #foru #babykittenrizz #babykitten #kitten...,...,NaN,kitty.rizzler,Kitty Rizzler,NaN,NaN,NaN,NaN,NaN,False,"[fyp, foru, babykittenrizz, babykitten, kitten..."
587,7280444523203808554,2023-09-19T04:03:18,158.0,US,"[Pallas Cats, Cats Videos, Animal Videos, A...",113600.0,9421.0,582.0,852200.0,#wildlife #kitten #cat #animal,...,NaN,animaltracks789,Animal Tracks,NaN,NaN,NaN,NaN,NaN,False,"[wildlife, kitten, cat, animal]"

In [14]:
def filter_conditions(row):
    has_hashtag = isinstance(row['hashtags'], list) and any(hashtag in row['hashtags'] for hashtag in hashtags_list)
    is_creator = row['author_username'] in creaters_list
    has_suggested_word = isinstance(row['suggested_words'], list) and any(word in row['suggested_words'] for word in hashtags_list)
    
    return has_hashtag or is_creator or has_suggested_word

data_to_filter_result = data_to_filter[data_to_filter.apply(filter_conditions, axis=1)]

## if hashtags is indeed a list, check if there is overlap between the video hashtag and the hashtag list or if the video 
## content creator is a news account. If any of the two is satisfied, pass to new dataset newsDF.

In [15]:
data_to_filter_result
## This result is actually a bit too weird

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,...,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified,hashtags
144,7285749180025408811,2023-10-03T14:30:00,41.0,US,"[bogo sort, Bubble Sort, sorting algorithms,...",740300.0,18800.0,4338.0,10400000.0,#quicksort #mergesort #sorting #algorithms #vi...,...,NaN,sort_everything176,sort_vizual,NaN,NaN,NaN,NaN,NaN,False,"[quicksort, mergesort, sorting, algorithms, vi..."
183,7280588242024402218,2023-09-19T13:22:27,62.0,US,[],397600.0,393700.0,33900.0,11700000.0,Facts that could save your life‚ÄºÔ∏è | Part 11 | ...,...,NaN,factsfromnez,Nez,NaN,NaN,NaN,NaN,NaN,False,"[curiosity, randomfacts, learnontiktok, factsy..."
247,7282169818021645610,2023-09-23T19:38:12,205.0,US,[],565800.0,2801.0,3842.0,8200000.0,#fyp„Ç∑ #cops #foryou #cps #fyp #911 #police #ne...,...,NaN,jeam5389,CRAZY COPS,NaN,NaN,NaN,NaN,NaN,False,"[fyp„Ç∑, cops, foryou, cps, fyp, 911, police, ne..."
252,7284389787144916270,2023-09-29T19:13:46,103.0,US,[],1300000.0,299500.0,91100.0,12500000.0,Video shows the events leading up to the shoot...,...,NaN,nbcwashington,NBC Washington,NaN,NaN,NaN,NaN,NaN,True,"[dc, washingtondc, districtofcolumbia, dmvnews..."
493,7281629597169405226,2023-09-22T08:41:53,132.0,US,[],98700.0,3097.0,992.0,1100000.0,Conway is amazing #math #learnontiktok #stem #...,...,NaN,average_joe_mcc,Average Joe,NaN,NaN,NaN,NaN,NaN,False,"[math, learnontiktok, stem, science, mathteacher]"
524,7281705059778383147,2023-09-22T13:34:48,34.0,US,"[bedford high school, bedford high school tra...",410800.0,67400.0,9383.0,3500000.0,"Disciplinary action is still being discussed, ...",...,NaN,nbc10boston,NBC10 Boston,NaN,NaN,NaN,NaN,NaN,True,"[newhampshire, school, news, video, fyp]"

In [16]:
file_name = 'new_relevant_videos.csv' #change as needed
with open(file_name, 'w') as fout:
    data_to_filter_result.to_csv('news_relevant_videos_48271.csv')